<a href="https://colab.research.google.com/github/Muhaiminul-Hasan/Writing-poetry-from-Irish-songs-using-NLP/blob/main/Writing_Poetry_using_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, Dropout

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import io
import json
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
tokenizer = Tokenizer()

data = "You just want attention, you dont want my heart \n Maybe you just hate the thought of me with someone new"
corpus = data.lower().split("\n")

tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1

print(corpus[0:2])

['you just want attention, you dont want my heart ', ' maybe you just hate the thought of me with someone new']


In [ ]:
input_sequences = []
for line in corpus:
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequences.append(n_gram_sequence)

print(input_sequences)

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 1], [1, 2, 3, 4, 1, 5], [1, 2, 3, 4, 1, 5, 3], [1, 2, 3, 4, 1, 5, 3, 6], [1, 2, 3, 4, 1, 5, 3, 6, 7], [8, 1], [8, 1, 2], [8, 1, 2, 9], [8, 1, 2, 9, 10], [8, 1, 2, 9, 10, 11], [8, 1, 2, 9, 10, 11, 12], [8, 1, 2, 9, 10, 11, 12, 13], [8, 1, 2, 9, 10, 11, 12, 13, 14], [8, 1, 2, 9, 10, 11, 12, 13, 14, 15], [8, 1, 2, 9, 10, 11, 12, 13, 14, 15, 16]]


In [ ]:
max_sequence_len = max([len(x) for x in input_sequences])
max_sequence_len = 20
print(max_sequence_len)

20


In [ ]:
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
print(input_sequences)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1  5  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1  5  3  6]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1  5  3  6  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10 11]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10 11 12]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10 11 12 13]
 [ 0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10 11 12

In [ ]:
xs = input_sequences[:,:-1]
labels = input_sequences[:,-1]
ys = tf.keras.utils.to_categorical(labels, num_classes = total_words)

print(xs)
print(labels)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1  5  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  1  5  3  6]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10 11]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10 11 12]
 [ 0  0  0  0  0  0  0  0  0  0  0  8  1  2  9 10 11 12 13]
 [ 0  0  0  0  0  0  0  0  0  0  8  1  2

In [ ]:
model = Sequential([
    Embedding(total_words, 240, input_length=max_sequence_len - 1),
    Bidirectional(LSTM(150, return_sequences=True)),
    LSTM(100),
    Dense(total_words, activation='softmax')
])

In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 19, 240)           4080      
                                                                 
 bidirectional_3 (Bidirecti  (None, 19, 300)           469200    
 onal)                                                           
                                                                 
 lstm_7 (LSTM)               (None, 100)               160400    
                                                                 
 dense_3 (Dense)             (None, 17)                1717      
                                                                 
Total params: 635397 (2.42 MB)
Trainable params: 635397 (2.42 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
history = model.fit(xs, ys, epochs = 100, verbose = 1)

Epoch 1/100
1/1 [==============================] - 7s 7s/step - loss: 2.8304 - accuracy: 0.0556
Epoch 2/100
1/1 [==============================] - 0s 17ms/step - loss: 2.7979 - accuracy: 0.1111
Epoch 3/100
1/1 [==============================] - 0s 17ms/step - loss: 2.7607 - accuracy: 0.1667
Epoch 4/100
1/1 [==============================] - 0s 17ms/step - loss: 2.7147 - accuracy: 0.1111
Epoch 5/100
1/1 [==============================] - 0s 18ms/step - loss: 2.6660 - accuracy: 0.1667
Epoch 6/100
1/1 [==============================] - 0s 17ms/step - loss: 2.6443 - accuracy: 0.1111
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 2.6291 - accuracy: 0.1667
Epoch 8/100
1/1 [==============================] - 0s 17ms/step - loss: 2.5859 - accuracy: 0.1667
Epoch 9/100
1/1 [==============================] - 0s 17ms/step - loss: 2.5405 - accuracy: 0.2222
Epoch 10/100
1/1 [==============================] - 0s 20ms/step - loss: 2.5034 - accuracy: 0.2222
Epoch 11/100
1/1 [===

In [ ]:
seed_text = "You dont hate my heart"
next_words = 20

In [ ]:
for _ in range(next_words):
  token_list = tokenizer.texts_to_sequences([seed_text])[0]
  token_list = pad_sequences([token_list], maxlen = max_sequence_len-1, padding='pre')
  predicted = model.predict(token_list, verbose=0)
  predicted_index = np.argmax(predicted)
  output_word = ""
  for word, index in tokenizer.word_index.items():
    if index == predicted_index:
      output_word = word
      break
  seed_text += " " + output_word
print(seed_text)

You dont hate my heart attention dont want heart heart heart heart new new new new new new new my new new new new new
